# Generated by Django 3.0.3 on 2020-02-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Cognoms', models.CharField(max_length=30)),
                ('Torn', models.CharField(choices=[('MR', 'Morning'), ('AT', 'Afternoon'), ('WD', 'Whole day')], max_length=2)),
                ('Telèfon', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciutat', models.CharField(max_length=30)),
                ('carrer', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Cognoms', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Telèfon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberShopApp.Barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberShopApp.Client')),
            ],
        ),
    ]
