# Generated by Django 3.0.3 on 2020-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='Torn',
            field=models.CharField(choices=[('MR', 'Matí'), ('AT', 'Tarda'), ('WD', 'Tot el dia')], max_length=2),
        ),
    ]
