# Generated by Django 3.0.3 on 2020-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text=None, max_length=60, unique=True),
        ),
    ]
