# Generated by Django 3.0.3 on 2020-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberia',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
