# Generated by Django 3.0.3 on 2020-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0002_auto_20200313_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=9, null=True, verbose_name='Telèfon'),
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(choices=[('H', 'Home'), ('D', 'Dona'), ('A', 'Altre')], default='Altre', max_length=10, verbose_name='Sexe'),
        ),
    ]
