# Generated by Django 3.0.3 on 2020-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0003_auto_20200309_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberia',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
