# Generated by Django 3.0.3 on 2020-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberShopApp', '0003_auto_20200314_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name="Nom d'usuari"),
        ),
    ]
